spring:
  application:
    name: zzu_miao
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zzu_miao?serverTimezone=UTC
    username: root
    password: qwer
  rsocket:
    server:
      port: 8080
  redis:
    host: 192.168.204.129
    port: 6379
    password: qwer
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
      shutdown-timeout: 5000
    database: 1

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

mybatis-plus:
  mapper-locations:
    classpath: mappers/*xml
  type-aliases-package: com.miao.domain

  global-config:
    db-config:
      # 配置mybatis-plus 逻辑删除
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

