spring:
  application:
    name: zzu_miao
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zzu_miao?serverTimezone=UTC
    username: root
    password: qwer
  rsocket:
    server:
      port: 8080
  redis:
    #    host: 192.168.204.129
    host: 82.157.176.239
    port: 6379
#    password: qwer
    password: woshidhx123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
      shutdown-timeout: 5000
    database: 1

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

  servlet:
    multipart:
      max-file-size: 20MB

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
mybatis-plus:
  mapper-locations:
    classpath: mappers/*xml
  type-aliases-package: com.miao.domain

  global-config:
    db-config:
      # 配置mybatis-plus 逻辑删除
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 这些配置在腾讯云控制台都可查到（使用时替换为你自己的）
# 腾讯云的SecretId（永久的，可在控制台开启或关闭）
tencent:
  secretId: AKIDhSrAKOZdZK5nw1BRYYQdllbIvU4Vnwzv
  # 腾讯云的SecretKey（永久的，可在控制台开启或关闭）
  secretKey: sbfZKvMF5e6O4iEcr6ED4pRzRn1Z5ZxG
  # 腾讯云的bucket (存储桶)
  bucket: zzu-miao-1025-1308522872
  # 腾讯云的region(bucket所在地区)
  region: ap-nanjing
  # 腾讯云的访问基础链接:
  baseUrl: https://zzu-miao-1025-1308522872.cos.ap-nanjing.myqcloud.com/
